### ISSUE TITLE
Pre Analysis not working when using av1.

### ISSUE THREAD

**Issue by timuryn** [rigaya/VCEEnc#107]
When I use this command:
VCEEncC64 -i 0.mp4 --audio-copy --chapter-copy -c av1 --vbr 600 --bframes 3 --ref 5 --gop-len 100 --b-pyramid --preset slower --level auto --motion-est q-pel --pa sc=high,ss=high,activity-type=yuv,paq=caq,taq=on,lookahead=32 --colorrange auto --avsync cfr --vpp-deband --vpp-edgelevel --vpp-warpsharp -o 1.mkv

The encoding halt to indefinitely and won't start ever, here is the log:

C:\0portable\0video\VCEEncC_8.22_x64>VCEEncC64 -i 0.mp4 --audio-copy --chapter-copy -c av1 --vbr 600 --bframes 3 --ref 5 --gop-len 100 --b-pyramid --preset slower --level auto --motion-est q-pel --pa sc=high,ss=high,activity-type=yuv,paq=caq,taq=on,lookahead=32 --colorrange auto --avsync cfr --vpp-deband --vpp-edgelevel --vpp-warpsharp -o 1.mkv
--------------------------------------------------------------------------------
1.mkv
--------------------------------------------------------------------------------
VCEEnc (x64) 8.22 (r1633) by rigaya, Mar 12 2024 12:48:59 (VC 1938/Win)
OS:            Windows 11 x64 (22631) [UTF-8]
CPU:           AMD Ryzen 5 7600 6-Core Processor [5.16GHz] (6C/12T)
GPU:           AMD Radeon RX 7900 GRE [31.0.24027.1012]
AMF:           Runtime 1.4.33 / SDK 1.4.30
Input Info:    avvce: H.265/HEVC, 1280x720, 25/1 fps
VPP            cspconv(nv12 -> yv12)
               edgelevel: strength 5.0, threshold 20.0, black 0.0, white 0.0
               warpsharp: threshold 128.0, blur 2, type 0, depth 16.0, chroma 0
               deband: mode 1, range 15, threY 15, threCb 15, threCr 15
                       ditherY 15, ditherC 15, blurFirst no, randEachFrame no
               cspconv(yv12 -> nv12)
Output:        AV1  main @ Level 5.2
               1280x720p 0:0 25.000fps (25/1fps)
               avwriter: av1, vorbis => matroska
Quality:       slower
VBR:           600 kbps
Max bitrate:   900 kbps
QP:            Min: 1:1, Max: 255:255
VBV Bufsize:   600 kb
Pre Analysis:  sc high, ss high, activity yuv
               lookahead 32, caq medium, paq caq, taq 1, motion-qual none, ltr off
Ref frames:    5 frames
LTR frames:    0 frames
Motion Est:    full-pel
Tiles:         1
GOP Len:       100 frames
Temporal Lyrs: 1
ScreenContent: on,palette-mode off, force-integer-mv off
VUI:              range:limited
Others:        skipframe:on deblock aq:off cdef:on cdf-update:on cdf-frame-end-update:on

**Comment by DimkaTsv** [comment]
@timuryn For information purposes. --pa taq=on is invalid, as taq argument only takes integers 0, 1 or 2 responsible for levels.
Also if you enable taq, paq=caq becomes overridden as they are replacing each other, not working at the same time. 

Now that is some WEIRD log i got... 
I don't think it is supposed to return any sort of source code.
[vceencc_log.txt](https://github.com/rigaya/VCEEnc/files/14892592/vceencc_log.txt)

Lines 4157--6721

I will note particular thing though:
```
--------------------------------------------------------------------------
build log of gfx1101...
C:\Users\DimkaTsv\AppData\Local\Temp\comgr-bc8012\input\CompileSource:43:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
#pragma once
        ^
C:\Users\DimkaTsv\AppData\Local\Temp\comgr-bc8012\input\CompileSource:86:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
#pragma once
        ^
C:\Users\DimkaTsv\AppData\Local\Temp\comgr-bc8012\input\CompileSource:280:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
#pragma once
        ^
3 warnings generated.

--------------------------------------------------------------------------
```
@rigaya Looks like code snippets in debug log are specific to vpp filters. And one that errors out on compilation is first code snipper from --vpp-deband filter. I checked other two filters and all code snippets coming from these commands and all except that first snippet compiled properly. 

Anyways, back to main problem of TS...
Issue also reproducible with basic command, aka just AV1 codec, VBR and PA. Nothing more:
%~dp0\VCEEncC64.exe -i %1 -o "%~n1_processed%~x1" --codec av1 --vbr 6000 --pa --audio-copy --log vceencc_log.txt --log-level debug
Meaning that problem is specific to AV1 + Preanalysis combination. HEVC and AVC work properly. 
Tried with AMF direct Transcode HW:
`%~dp0\TranscodeHW.exe -input %1 -output %~n1_TranscodeHW%~x1 -codec AV1 -Av1RateControlMethod VBR -Av1TargetBitrate 20000000 -Av1EnablePreAnalysis true`
This worked out fine, meaning problem should be VCEEnc specific.

**Comment by timuryn** [comment]
> I don't have any problem with AV1 + PA with VCEEnc 8.23 and 24.6.1 driver at RX7900XT.
> 
> I think driver update shall fix this issue.

You right, thanks. With updated drivers, there are no issues.
