### ISSUE TITLE
Error reported by a user of Staxrip with AMD H264 - FPS in out file not equal to output fps.

### ISSUE THREAD

**Issue by 44vince44** [rigaya/VCEEnc#25]
Dear @rigaya ,

one of the users of staxrip encountered an error with VCEEnc.
Unfortunately we have no AMD hardware to check by ourselves.

The problems happens with **AMD.H264 ONLY** (not with AMD.H265)

The input and output are 90FPS, but the real output will be 30fps (no frames skipped, so the video is 3 times longer).

Here is the verbose of VCEEnc:

![SNAG-0000](https://user-images.githubusercontent.com/17828567/114405365-4ab6ad00-9baf-11eb-85bb-12b5941d08ab.jpg)

And here is the mediainfo of the real output file

![SNAG-0001](https://user-images.githubusercontent.com/17828567/114405424-56a26f00-9baf-11eb-990e-60f780085f03.jpg)

Thanks for helping!

Here are the logs provided by user @nulledone
[amdlogfiles.zip](https://github.com/rigaya/VCEEnc/files/6297238/amdlogfiles.zip)

**Comment by rigaya** [comment]
I've got weird results here, it seems like this problem is specific to RX5xxx series.

I've tested exactly the same options with RX460 and RX5500XT, but I only got this problem from RX5500XT.

**Left: RX460, Right: RX5500XT**
![image](https://user-images.githubusercontent.com/815947/114552320-7022e400-9c9f-11eb-902b-9e46ddadfc50.png)![image](https://user-images.githubusercontent.com/815947/114553163-503ff000-9ca0-11eb-86ce-bb0b5ce08663.png)

I'll check further what is going on here.

**Comment by 44vince44** [comment]
Thanks very much ! I hope you'll find the problem !

**Comment by 44vince44** [comment]
I am closing this thread now. When the tool is updated with a fix, the following release of Staxrip will include it.

**Comment by rigaya** [comment]
Thank you for letting me know the problem.

I think I've found the problem, the updated [VCEEnc 6.10](https://github.com/rigaya/VCEEnc/releases/tag/6.10) won't have this problem anymore.

![image](https://user-images.githubusercontent.com/815947/115094432-70013d80-9f58-11eb-8be1-502453b8bb8a.png)

**Comment by 44vince44** [comment]
Many Thanks @rigaya  !!!  👍🏼 

@nulledone please test (just replace files of path StaxRip\Apps\Encoders\VCEEnc\ with the one of the release here)

**Comment by nulledone** [comment]
Seems to be working well, thanks!
